(define (problem BLOCKS-11-2)
(:domain BLOCKS)
(:objects A B C D E F G H I J K )
(:INIT (CLEAR B) (CLEAR I) (ONTABLE K) (ONTABLE A) (ON B D) (ON D F) 
 (ON F H) (ON H K) (ON I C) (ON C E) (ON E G) (ON G J) (ON J I) (ON I A)
 (HANDEMPTY))
(:goal (AND (ON K A) (ON A J) (ON J B) (ON B I) (ON I C) (ON C H) (ON H D)
            (ON D G) (ON G E) (ON E F)))
)