(define (problem BLOCKS-13-4)
(:domain BLOCKS)
(:objects L H E A J C D F G K M I B )
(:INIT (CLEAR B) (CLEAR I) (ONTABLE L) (ONTABLE E) (ON B F) (ON F D) 
 (ON D C) (ON C L) (ON I A) (ON A H) (ON H G) (ON G K) (ON K M) (ON M J)
 (ON J E) (HANDEMPTY))
(:goal (AND (ON A E) (ON E L) (ON L M) (ON M C) (ON C K) (ON K D) (ON D H)
            (ON H I) (ON I B) (ON B J) (ON J F) (ON F G)))
)