(define (problem BLOCKS-10-2)
(:domain BLOCKS)
(:objects B G E D F H I A C J )
(:INIT (CLEAR B) (CLEAR C) (ONTABLE J) (ONTABLE A) (ON B H) (ON H E) (ON E I)
 (ON I F) (ON F J) (ON C D) (ON D G) (ON G A) (HANDEMPTY))
(:goal (AND (ON B G) (ON G E) (ON E D) (ON D F) (ON F H) (ON H I) (ON I A)
            (ON A C) (ON C J)))
)