(define (problem BLOCKS-8-1)
(:domain BLOCKS)
(:objects B H F G E D A C )
(:INIT (CLEAR D) (CLEAR A) (CLEAR E) (ONTABLE G) (ONTABLE H) (ONTABLE C) 
 (ON D B) (ON B G) (ON A F) (ON F H) (ON E C) (HANDEMPTY))
(:goal (AND (ON B H) (ON H F) (ON F G) (ON G A) (ON A D) (ON D E) (ON E C)))
)