(define (problem BLOCKS-10-4)
(:domain BLOCKS)
(:objects E J A I C D B G F H )
(:INIT (CLEAR J) (CLEAR C) (CLEAR B) (CLEAR H) (ONTABLE A) (ONTABLE C)
 (ONTABLE E) (ONTABLE H) (ON J G) (ON G I) (ON I F) (ON F D) (ON D A)
 (ON B E) (HANDEMPTY))
(:goal (AND (ON G H) (ON H C) (ON C A) (ON A F) (ON F J) (ON J D) 
	    (ON D I) (ON I E) (ON E B)))
)