(define (problem BLOCKS-7-3)
(:domain BLOCKS)
(:objects B D C F G A E )
(:INIT (CLEAR G) (CLEAR E) (ONTABLE C) (ONTABLE D) (ON G A) (ON A C)
 (ON E B) (ON B F) (ON F D) (HANDEMPTY))
(:goal (AND (ON G B) (ON B A) (ON A D) (ON D F) (ON F C) (ON C E)))
)