(define (problem BLOCKS-12-5)
(:domain BLOCKS)
(:objects L H E A J C D F G K I B )
(:INIT (CLEAR B) (ONTABLE G) (ON B C) (ON C F) (ON F H) (ON H A) (ON A E)
 (ON E I) (ON I L) (ON L D) (ON D J) (ON J G) (ON GK) (HANDEMPTY))
(:goal (AND (ON G I) (ON I C) (ON C D) (ON D F) (ON F A) (ON A H) (ON H E)
            (ON E L) (ON L J) (ON J B) (ON B K)))
)