(define (problem BLOCKS-11-4)
(:domain BLOCKS)
(:objects H E A J C D F G K I B )
(:INIT (CLEAR B) (CLEAR C) (CLEAR E) (ONTABLE K) (ONTABLE G) (ONTABLE H)
 (ON B D) (ON D I) (ON I K) (ON C A) (ON A J) (ON J F) (ON F G) (ON E H)
 (HANDEMPTY))
(:goal (AND (ON G I) (ON I C) (ON C D) (ON D F) (ON F A) (ON A M) (ON M H)
            (ON H E) (ON E L) (ON L J) (ON J B) (ON B K)))
)