(define (problem BLOCKS-12-4)
(:domain BLOCKS)
(:objects  A F H I L B D E C J G K )
(:INIT (CLEAR A) (CLEAR B) (CLEAR C) (ONTABLE J) (ONTABLE K) (ONTABLE L) 
 (ON A D) (ON D J) (ON B G) (ON G K) (ON C E) (ON E F) (ON F H) (ON H I)
 (ON I L) (HANDEMPTY))
(:goal (AND (ON G I) (ON I C) (ON C D) (ON D F) (ON F A) (ON A H) (ON H E)
            (ON E L) (ON L J) (ON J B) (ON B K)))
)