(define (problem BLOCKS-10-5)
(:domain BLOCKS)
(:objects J I H G F E D C B A )
(:INIT (CLEAR H) (CLEAR A) (CLEAR D) (ONTABLE G) (ONTABLE A) (ONTABLE C)
 (ON H J) (ON J I) (ON I G) (ON D E) (ON E F) (ON F B) (ON B C) (HANDEMPTY))
(:goal (AND (ON J I) (ON I H) (ON H G) (ON G F) (ON F E) (ON E D) (ON D C)
            (ON C B) (ON B A)))
)