(define (problem BLOCKS-13-3)
(:domain BLOCKS)
(:objects H E J C D K B A M I F L G )
(:INIT (CLEAR E) (CLEAR A) (CLEAR M) (ONTABLE I) (ONTABLE G) (ONTABLE K)
 (ON E I) (ON A D) (ON D C) (ON C G) (ON M J) (ON J B) (ON B H) (ON H F)
 (ON F K) (HANDEMPTY))
(:goal (AND (ON H E) (ON E J) (ON J C) (ON C D) (ON D K) (ON K B) (ON B A)
            (ON A M) (ON M I) (ON I F) (ON F L) (ON L G)))
)