(define (problem BLOCKS-12-1)
(:domain BLOCKS)
(:objects A D G J L B C E F H I K )
(:INIT (CLEAR B) (CLEAR I) (ONTABLE K) (ONTABLE G) (ON B F) (ON F D) 
 (ON D C) (ON C J) (ON J A) (ON A E) (ON E H) (ON H L) (ON L K) (ON I G)
 (HANDEMPTY))
(:goal (AND (ON A B) (ON B C) (ON C D) (ON D E) (ON E F) (ON F G) (ON G H)
            (ON H I) (ON I J) (ON J K) (ON K L)))
)