(define (problem BLOCKS-12-3)
(:domain BLOCKS)
(:objects L H E A J C D F G K I B )
(:INIT (CLEAR H) (CLEAR I) (CLEAR K) (ONTABLE B) (ONTABLE G) (ONTABLE K)
 (ON H E) (ON E D) (ON D B) (ON I L) (ON L A) (ON A C) (ON C F) (ON F J)
 (ON J K) (ON K G) (HANDEMPTY))
(:goal (AND (ON G I) (ON I C) (ON C D) (ON D F) (ON F A) (ON A H) (ON H E)
            (ON E L) (ON L J) (ON J B) (ON B K)))
)