(define (problem BLOCKS-10-5)
(:domain BLOCKS)
(:objects J I H G F E D C B A )
(:INIT (CLEAR J) (CLEAR F) (CLEAR G) (ONTABLE B) (ONTABLE A) (ONTABLE C)
 (ON J H) (ON H B) (ON F E) (ON E A) (ON G I) (ON I D) (ON D C)
 (HANDEMPTY))
(:goal (AND (ON J I) (ON I H) (ON H G) (ON G F) (ON F E) (ON E D) (ON D C)
            (ON C B) (ON B A)))
)