(define (problem BLOCKS-8-1)
(:domain BLOCKS)
(:objects B H F G E D A C )
(:INIT (CLEAR D) (CLEAR A) (CLEAR E) (CLEAR H) (CLEAR C) (ONTABLE G)
 (ONTABLE A) (ONTABLE E) (ONTABLE H) (ONTABLE C) (ON D B) (ON B F) (ON F G)
 (HANDEMPTY))
(:goal (AND (ON H G) (ON G F) (ON F E) (ON E D) (ON D C) (ON C B) (ON B A)))
)