(define (problem BLOCKS-8-0)
(:domain BLOCKS)
(:objects D H E F C A G B )
(:INIT (CLEAR E) (CLEAR G) (ONTABLE F) (ONTABLE H) (ON E A) (ON A C) (ON C F)
 (ON G D) (ON D B) (ON B H) (HANDEMPTY))
(:goal (AND (ON E A) (ON A C) (ON C F) (ON F G) (ON G D) (ON D B) (ON B H)))
)